#!/usr/bin/env bash

# Copyright 2024 Raffaele Mancuso
# SPDX-License-Identifier: MIT

# Requires wf-recorder: https://github.com/ammen99/wf-recorder

SIGNAL=1
pidf="/tmp/ags-screenrecorder"
WF_RECORDER_OPTS=""
# Insert `--audio` if you want to record audio
# Specify video codec
# find available video codecs with `ffmpeg -encoders`
WF_RECORDER_OPTS="$WF_RECORDER_OPTS -c h264_vaapi -d /dev/dri/renderD128 --bframes 0"
# Specify audio codec
# find available audio codecs with `ffmpeg -codecs`
# WF_RECORDER_OPTS="$WF_RECORDER_OPTS --audio --codec opus"
# printf "WF_RECORDER_OPTS=%s\n" "$WF_RECORDER_OPTS"
VIDEOEXT="mp4"

if [ "$1" == "status" ]; then
	if [ -s "$pidf" ]; then
		echo "recording"
	else
		echo "not recording"
	fi

elif [ "$1" == "toggle" ]; then
	if [ -s "$pidf" ]; then
		pid=$(awk 'NR==1' "$pidf")
		kill "$pid"
		printf "" > "$pidf"
	else
		mkdir -p "$HOME/Videos/Screencasts"
		bf="$HOME/Videos/Screencasts/$(date +%Y-%m-%d_%H-%M-%S)"
		vidf="$bf.$VIDEOEXT"
		logf="$bf.log"
		if [ "$2" == "fullscreen" ]; then
			monitor_info=$(hyprctl -j monitors | jq -r ".[] | select(.name == \"$3\")")
			echo "Monitor Selected: $3" > "$logf"
			w=$(echo $monitor_info | jq -r '.width')
			h=$(echo $monitor_info | jq -r '.height')
			x=$(echo $monitor_info | jq -r '.x')
			y=$(echo $monitor_info | jq -r '.y')
			g_arg="${x},${y} ${w}x${h}"
			wf-recorder $WF_RECORDER_OPTS --geometry "$g_arg" --file "$vidf" 1>>"$logf" 2>&1 &
		elif [ "$2" == "region" ]; then
			wf-recorder $WF_RECORDER_OPTS --geometry "$(slurp)" --file "$vidf" 1>"$logf" 2>&1 &
		else
			printf "Argument \$2='%s' not valid (fullscreen/region)" "$2"
			exit
		fi
		pid=$(jobs -p | tail -n 1)
		printf "%d\n%s\n%s" "$pid" "$vidf" "$logf" > "$pidf"
		disown "$pid"
	fi
else
	printf "ERROR: Argument %s not valid\n" "$1"
fi
